const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="rodricksector2814@gmail.com"
global.location="That one"


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "XXXAVIER" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "256709150527";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "256782956464";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_22_06_05_23_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM2LFxuICAgICAgICAwLFxuICAgICAgICA1OSxcbiAgICAgICAgMTkwLFxuICAgICAgICAzNixcbiAgICAgICAgMzUsXG4gICAgICAgIDI0NSxcbiAgICAgICAgOTMsXG4gICAgICAgIDUwLFxuICAgICAgICAxNTQsXG4gICAgICAgIDIwLFxuICAgICAgICAxNTYsXG4gICAgICAgIDY0LFxuICAgICAgICAyMzAsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjE0LFxuICAgICAgICAyNDMsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTEyLFxuICAgICAgICAyMixcbiAgICAgICAgMzksXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTYsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMjM5LFxuICAgICAgICAxNDQsXG4gICAgICAgIDYxLFxuICAgICAgICAxNTcsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjU1LFxuICAgICAgICA1NixcbiAgICAgICAgMTAxXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDg4LFxuICAgICAgICA4NixcbiAgICAgICAgNzMsXG4gICAgICAgIDExNixcbiAgICAgICAgMjgsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTg4LFxuICAgICAgICA4NyxcbiAgICAgICAgNjUsXG4gICAgICAgIDIyMCxcbiAgICAgICAgNzAsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTIsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxODUsXG4gICAgICAgIDMsXG4gICAgICAgIDIwNixcbiAgICAgICAgNTQsXG4gICAgICAgIDkwLFxuICAgICAgICAyMDksXG4gICAgICAgIDI1NSxcbiAgICAgICAgNTcsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjI4LFxuICAgICAgICAyMzEsXG4gICAgICAgIDEyNixcbiAgICAgICAgMjUsXG4gICAgICAgIDc4LFxuICAgICAgICAxMzEsXG4gICAgICAgIDQsXG4gICAgICAgIDM4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3MixcbiAgICAgICAgMTA4LFxuICAgICAgICAxNTYsXG4gICAgICAgIDIxMCxcbiAgICAgICAgNjYsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTYzLFxuICAgICAgICAzMSxcbiAgICAgICAgMTQsXG4gICAgICAgIDI1MCxcbiAgICAgICAgOTcsXG4gICAgICAgIDEyOSxcbiAgICAgICAgNDEsXG4gICAgICAgIDEwNixcbiAgICAgICAgNDAsXG4gICAgICAgIDYxLFxuICAgICAgICA4OSxcbiAgICAgICAgMzksXG4gICAgICAgIDE1LFxuICAgICAgICAxMDMsXG4gICAgICAgIDIzMSxcbiAgICAgICAgOTUsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTg0LFxuICAgICAgICAxNCxcbiAgICAgICAgMTkzLFxuICAgICAgICAxMzMsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMjQyLFxuICAgICAgICA5OSxcbiAgICAgICAgMTc2LFxuICAgICAgICA5OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAzOCxcbiAgICAgICAgMTAyLFxuICAgICAgICAyNDQsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTk2LFxuICAgICAgICAyMzYsXG4gICAgICAgIDE2MCxcbiAgICAgICAgNTUsXG4gICAgICAgIDYwLFxuICAgICAgICAxMjEsXG4gICAgICAgIDYwLFxuICAgICAgICA5MyxcbiAgICAgICAgMzMsXG4gICAgICAgIDYxLFxuICAgICAgICA1NSxcbiAgICAgICAgMjI4LFxuICAgICAgICA4NCxcbiAgICAgICAgMTIwLFxuICAgICAgICAyMTUsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTYyLFxuICAgICAgICAxMjYsXG4gICAgICAgIDEwLFxuICAgICAgICAyNDksXG4gICAgICAgIDI3LFxuICAgICAgICAyMjAsXG4gICAgICAgIDc0LFxuICAgICAgICA0NCxcbiAgICAgICAgMTkzLFxuICAgICAgICAyMzcsXG4gICAgICAgIDE4LFxuICAgICAgICAzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzIsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTY1LFxuICAgICAgICAyMDIsXG4gICAgICAgIDQwLFxuICAgICAgICAxODgsXG4gICAgICAgIDM3LFxuICAgICAgICAxMzksXG4gICAgICAgIDIzNyxcbiAgICAgICAgMjM3LFxuICAgICAgICAxOTUsXG4gICAgICAgIDI0MixcbiAgICAgICAgNDEsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjksXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTksXG4gICAgICAgIDY3LFxuICAgICAgICA5OCxcbiAgICAgICAgMjEwLFxuICAgICAgICA0OSxcbiAgICAgICAgMTQ3LFxuICAgICAgICA0MSxcbiAgICAgICAgMTg1LFxuICAgICAgICAxNixcbiAgICAgICAgMTkyLFxuICAgICAgICAxMjAsXG4gICAgICAgIDM0LFxuICAgICAgICAyMTEsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjQsXG4gICAgICAgIDExNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDYsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxNDAsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTIsXG4gICAgICAgIDU5LFxuICAgICAgICAxNDYsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTc3LFxuICAgICAgICA2LFxuICAgICAgICAyNDAsXG4gICAgICAgIDE2LFxuICAgICAgICAxMixcbiAgICAgICAgNTcsXG4gICAgICAgIDMyLFxuICAgICAgICAxNDksXG4gICAgICAgIDg4LFxuICAgICAgICA5NSxcbiAgICAgICAgMzcsXG4gICAgICAgIDU4LFxuICAgICAgICAyMTcsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMjMwLFxuICAgICAgICA4NCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxNzQsXG4gICAgICAgIDY3LFxuICAgICAgICA2OCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMTgsXG4gICAgICAgIDE3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxNCxcbiAgICAgICAgICA3MVxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDYsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMTI2LFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICA5NSxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICA0MCxcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAxMDhcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2NCxcbiAgICAgICAgOTMsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMjAsXG4gICAgICAgIDMxLFxuICAgICAgICAyMTYsXG4gICAgICAgIDYyLFxuICAgICAgICAyLFxuICAgICAgICAxOTEsXG4gICAgICAgIDU2LFxuICAgICAgICA1MyxcbiAgICAgICAgNDEsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTM4LFxuICAgICAgICAxNTIsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyMjksXG4gICAgICAgIDE2LFxuICAgICAgICAxMzYsXG4gICAgICAgIDU4LFxuICAgICAgICAyMDcsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTQ5LFxuICAgICAgICA3LFxuICAgICAgICAxMjYsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjQwLFxuICAgICAgICAxODEsXG4gICAgICAgIDU5LFxuICAgICAgICAxNjQsXG4gICAgICAgIDE5NyxcbiAgICAgICAgNzYsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTY3LFxuICAgICAgICAyMTcsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjQsXG4gICAgICAgIDIyMyxcbiAgICAgICAgNzksXG4gICAgICAgIDQsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTgwLFxuICAgICAgICAxMjEsXG4gICAgICAgIDE3MixcbiAgICAgICAgMjMwLFxuICAgICAgICA5MyxcbiAgICAgICAgODUsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTg0LFxuICAgICAgICAxMCxcbiAgICAgICAgMTkyLFxuICAgICAgICAxMDAsXG4gICAgICAgIDI0LFxuICAgICAgICAyMDQsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjAxLFxuICAgICAgICA1NyxcbiAgICAgICAgNTEsXG4gICAgICAgIDg3LFxuICAgICAgICAyNTEsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTgyLFxuICAgICAgICAxMzdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEwOCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJVUVNtOXl1TVdXN1BoMXBRK3lmeFNoMjdCMDZteUtsVXRLSXBVc1RDNTc4PVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI1Njc4Mjk1NjQ2NEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNzU3NzEzRTI5QTBCOThDRkMyMUNFQzI0RTE0Q0VDQUFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE2NTAxOTkxXG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU2NzgyOTU2NDY0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIzNjM3RjlEOUJFQzVBQzc1MUE1QkNEMzg3NUFFMEZDNFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTY1MDE5OTFcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDYxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDYxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiQmdYZEZuSDFTWjJ3SVBFTHlnamI1UVwiLFxuICBcInBob25lSWRcIjogXCI3ZjdiMjhjZi02OThhLTQ0NDItYjFmYi1mZjUyZTE1NzkzZjZcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTAyLFxuICAgICAgMTI0LFxuICAgICAgODksXG4gICAgICAyMTksXG4gICAgICAxODAsXG4gICAgICA3MCxcbiAgICAgIDEzOSxcbiAgICAgIDEzOSxcbiAgICAgIDMyLFxuICAgICAgOTcsXG4gICAgICAyMTYsXG4gICAgICA1MSxcbiAgICAgIDIzMSxcbiAgICAgIDQ4LFxuICAgICAgNTUsXG4gICAgICAyMTgsXG4gICAgICAyMjcsXG4gICAgICAxNDIsXG4gICAgICAxNjMsXG4gICAgICAxMjdcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTgyLFxuICAgICAgMjE3LFxuICAgICAgOTAsXG4gICAgICA2MSxcbiAgICAgIDI1MyxcbiAgICAgIDQxLFxuICAgICAgMjMzLFxuICAgICAgNTMsXG4gICAgICAxMzEsXG4gICAgICAxOTQsXG4gICAgICAxMzQsXG4gICAgICA4OSxcbiAgICAgIDIzNCxcbiAgICAgIDE1MCxcbiAgICAgIDk0LFxuICAgICAgMTE1LFxuICAgICAgMTAwLFxuICAgICAgMjE2LFxuICAgICAgMTU5LFxuICAgICAgMjAwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIjY4MTZXVEhTXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyNTY3ODI5NTY0NjQ6M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMzk2ODU5MzQwMjI2OTY6M0BsaWRcIixcbiAgICBcIm5hbWVcIjogXCJSSVAgVkFOIFdJTktMRVwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0tuZ2w4Z0RFT0Q3dnJJR0dBTWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiNUU4cnNTYmplb0NocDFwT2JHMlQ5bm8yMVptdjJ4NDFnUlRaY2liRFYxMD1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJzeE5zenNmbGszSm8rbW9ISXJRZjNMRGhlUUxkbmVqT1R3ZUE4ZjFWakcvRk01d2Vxd01IcTNEMjFScWcveWpDTVBSTnZ5WUw2YVhVZGhad1Q2VG9BQT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCI0enhjNGpSYndpcUQ1QU5aZ1E3aWxRSTJrUXoyYVk2UXAyZ2ZDQk9EK09vYk5UOGtocWdCamxHUitXZzB6cHAybjgwbUJCVWY0OWkwejFHM2ltREtqZz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyNTY3ODI5NTY0NjQ6M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMzgsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDEyMixcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICA3OCxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgOTNcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcxNjUwMTk4OCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUtMa1wiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS0xrLmpzb24iOiAie1wia2V5RGF0YVwiOlwiUXczUHpBajVDbC82MXhKQmRxMzZzeTAxK2IzYTJDMnRIOXNNNXVOVHAyYz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo5NTY2OTA0NzMsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcxNjA5MTkyMTg4NlwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || "#",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.7",
  caption : global.caption || "XXXAVIER " , // ```『 XXXAVIER 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Sector",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "XXAVIER",
  ownername:process.env.OWNER_NAME|| "ROD",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
